- name: Install pip and dependencies
  hosts: all
  become: yes
  tasks:
    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker and docker-compose via pip
      pip:
        name:
          - docker
          - docker-compose
        executable: pip3

    - name: Run container with docker_container module
      docker_container:
        name: wartest
        image: "{{ image }}"
        ports:
          - "8081:8080"
        state: started

 
